### ISSUE TITLE
Store authenticators/strategies/executors as arrays

### ISSUE THREAD

**Issue by Sekhmet** [snapshot-labs/sx-api#149]
Right now they are stored as string and are hard to work with. We should store them as arrays of strings and return them as such via API.

**Comment by bonustrack** [comment]
This will require some change on Checkpoint, currently it doesn't handle storing array. We may need to introduce JSON type for to address this, here: https://github.com/snapshot-labs/checkpoint/blob/eabfe6b99a1535c8198772aceba64f4d292fbcc7/src/graphql/controller.ts#L365 and parse the JSON when it's returned by the GraphQL API here https://github.com/snapshot-labs/checkpoint/blob/eabfe6b99a1535c8198772aceba64f4d292fbcc7/src/graphql/resolvers.ts . The alternative would be to store the strategies params in a new table but that would not be easy to use.
