### ISSUE TITLE
Improve query speed

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-api#157]
Currently it take ~1sec to resolve a simple query on SX-API, this is making the experience on UI too much slow. For some reason when testing in local it's actually faster, something must be wrong in our setup. We can try to move database and server on same location, if it doesn't work we will need to find others ways to address this issue.

**Comment by Sekhmet** [comment]
@bonustrack I think this is resolved after we moved our deployment to same geolocation?

**Comment by bonustrack** [comment]
@Sekhmet Yes, closing this issue this is not relevant anymore.
