### ISSUE TITLE
feat: add space attributes entity

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-api#171]
Add a `Attribute` entity for store all space parameters like Twitter Discord Treasury link etc.

```gql
type Space {
  id: String!
  ...
  attributes: [Attribute]! @derivedFrom(field: "space")
}

type Attribute {
  id: String!
  space: Space
  key: String
  value: Text
}
```
We would insert data in this format:

```js
{
  id: '0x123.../twitter',
  space: '0x123...',
  key: 'twitter',
  value: 'SnapshotLabs'
}
```

**Comment by Sekhmet** [comment]
We use different format now, because of TheGraph limitations (it's now entity under `metadata`).

We could implement it as described this issue here, but won't be possible on TheGraph as it will come from IPFS File Data Source and those cannot update entities, only create new ones.
