### ISSUE TITLE
fix: controller address should be stored without extra zero

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-api#172]
Currently the SX API store address with extra 0 in beginning, not the same as what we display in the UI, it create some issue see comment here: https://github.com/snapshot-labs/sx-ui/pull/426#issuecomment-1426333303 We should use the same format on both

**Comment by Sekhmet** [comment]
We currently format all addresses with `validateAndParseAddress` which I think makes sense for the API as it's consistent.

I prefer UI to use stable comparison format, like we do already: https://github.com/snapshot-labs/sx-ui/pull/736

I will close this issue for now. If you prefer to handle it differently we can reopen it.
