### ISSUE TITLE
bug: Out of range value for column 'scores_1'

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-api#189]
I see this error in the logs:
```
Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'scores_1' at row 1
```
<img width="1450" alt="image" src="https://github.com/snapshot-labs/sx-api/assets/16245250/ec6a5e10-9c18-480d-b32f-bdb86aec361c">

**Comment by Sekhmet** [comment]
Fixed in https://github.com/snapshot-labs/sx-api/pull/186
